-- OuvintePro - semente determinística de bairros de Sao Paulo (capital) por zona.
-- Usada como fallback do bot quando a IA falha (comparacao case/acento-insensitive).
-- Re-seed completo: limpa e popula com a lista canonica.

delete from public.bairros_zonas;

insert into public.bairros_zonas (bairro, zona) values
-- ZONA SUL
('Água Funda','Sul'),('Alto da Boa Vista','Sul'),('Americanópolis','Sul'),('Balneário São Francisco','Sul'),
('Brooklin','Sul'),('Brooklin Novo','Sul'),('Brooklin Paulista','Sul'),('Brooklin Velho','Sul'),
('Campo Belo','Sul'),('Campo Grande','Sul'),('Campo Limpo','Sul'),('Capela do Socorro','Sul'),
('Capão Redondo','Sul'),('Chácara Flora','Sul'),('Chácara Inglesa','Sul'),('Chácara Klabin','Sul'),
('Chácara Monte Alegre','Sul'),('Chácara Santo Antônio','Sul'),('Cidade Ademar','Sul'),('Cidade Dutra','Sul'),
('Cidade Monções','Sul'),('Cidade Vargas','Sul'),('Cidade Jardim','Sul'),('Cupecê','Sul'),('Cursino','Sul'),
('Embura','Sul'),('Engenheiro Marsilac','Sul'),('Grajaú','Sul'),('Granja Julieta','Sul'),('Guarapiranga','Sul'),
('Heliópolis','Sul'),('Ibirapuera','Sul'),('Indianópolis','Sul'),('Interlagos','Sul'),('Ipiranga','Sul'),
('Itaim Bibi','Sul'),('Jardim Aeroporto','Sul'),('Jardim Ângela','Sul'),('Jardim Clímax','Sul'),
('Jardim Consórcio','Sul'),('Jardim Dom Bosco','Sul'),('Jardim Europa','Sul'),('Jardim Herculano','Sul'),
('Jardim Leonor','Sul'),('Jardim Marajoara','Sul'),('Jardim Miriam','Sul'),('Jardim Oriental','Sul'),
('Jardim Petrópolis','Sul'),('Jardim Previdência','Sul'),('Jardim Prudência','Sul'),('Jardim Promissão','Sul'),
('Jardim São Luís','Sul'),('Jardim São Saverio','Sul'),('Jardim Umarizal','Sul'),('Marsilac','Sul'),
('Mirandópolis','Sul'),('Moema','Sul'),('Morro dos Ingleses','Sul'),('Morumbi','Sul'),('Panamby','Sul'),
('Paraíso','Sul'),('Parque Alves de Lima','Sul'),('Parque Bristol','Sul'),('Parque Cocaia','Sul'),
('Parque Colonial','Sul'),('Parque Doroteia','Sul'),('Parque Fongaro','Sul'),('Parque Independência','Sul'),
('Parque Jabaquara','Sul'),('Pedreira','Sul'),('Parelheiros','Sul'),('Planalto Paulista','Sul'),
('Real Parque','Sul'),('Sacomã','Sul'),('Santo Amaro','Sul'),('Saúde','Sul'),('Socorro','Sul'),
('São João Clímaco','Sul'),('Vila Alexandria','Sul'),('Vila Andrade','Sul'),('Vila Clementino','Sul'),
('Vila Conceição','Sul'),('Vila Cruzeiro','Sul'),('Vila Guarani','Sul'),('Vila Mariana','Sul'),
('Vila Mascote','Sul'),('Vila Olímpia','Sul'),('Vila Nova Conceição','Sul'),('Vila Santa Catarina','Sul'),
('Vila das Belezas','Sul'),('Vila das Mercês','Sul'),('Vila Joaniza','Sul'),('Jardim Sabará','Sul'),
('Jardim Santo Amaro','Sul'),('Jardim São Bento Novo','Sul'),('Jardim Varginha','Sul'),('Jardim das Imbuias','Sul'),
-- ZONA LESTE
('Água Rasa','Leste'),('Alto da Mooca','Leste'),('Vila Bertioga','Leste'),('Vila Carrão','Leste'),
('Carrão','Leste'),('Vila Formosa','Leste'),('Vila Clotilde','Leste'),('Vila Diva','Leste'),
('Vila Regente Feijó','Leste'),('Aricanduva','Leste'),('Jardim Aricanduva','Leste'),('Artur Alvim','Leste'),
('Cidade Patriarca','Leste'),('Vila Ré','Leste'),('Vila Nhocuné','Leste'),('Jardim Nordeste','Leste'),
('Vila Esperança','Leste'),('Belém','Leste'),('Belenzinho','Leste'),('Brás','Leste'),('Cangaíba','Leste'),
('Engenheiro Goulart','Leste'),('Jardim Penha','Leste'),('Penha','Leste'),('Cidade Líder','Leste'),
('Cidade Tiradentes','Leste'),('Santa Etelvina','Leste'),('Inácio Monteiro','Leste'),('Ermelino Matarazzo','Leste'),
('Jardim Belém','Leste'),('Guaianases','Leste'),('Itaim Paulista','Leste'),('Jardim Romano','Leste'),
('Jardim Helena','Leste'),('Vila Curuçá','Leste'),('Itaquera','Leste'),('Cidade A.E. Carvalho','Leste'),
('Vila Carmosina','Leste'),('Parque do Carmo','Leste'),('José Bonifácio','Leste'),('Lajeado','Leste'),
('Mooca','Leste'),('Parque da Mooca','Leste'),('Pari','Leste'),('Ponte Rasa','Leste'),('São Mateus','Leste'),
('Cidade São Mateus','Leste'),('São Miguel Paulista','Leste'),('São Miguel','Leste'),('Vila Jacuí','Leste'),
('São Rafael','Leste'),('Sapopemba','Leste'),('Fazenda da Juta','Leste'),('Tatuapé','Leste'),
('Jardim Anália Franco','Leste'),('Vila Gomes Cardim','Leste'),('Vila Azevedo','Leste'),('Vila Matilde','Leste'),
('Vila Guilhermina','Leste'),('Vila Prudente','Leste'),('Vila Alpina','Leste'),('Vila Ema','Leste'),
('Vila Zelina','Leste'),('Parque São Lucas','Leste'),('Iguatemi','Leste'),('Parque São Rafael','Leste'),
-- ZONA NORTE
('Casa Verde','Norte'),('Casa Verde Alta','Norte'),('Casa Verde Baixa','Norte'),('Cachoeirinha','Norte'),
('Vila Nova Cachoeirinha','Norte'),('Jardim Peri','Norte'),('Freguesia do Ó','Norte'),('Brasilândia','Norte'),
('Limão','Norte'),('Santana','Norte'),('Alto de Santana','Norte'),('Santa Teresinha','Norte'),
('Chora Menino','Norte'),('Tucuruvi','Norte'),('Parada Inglesa','Norte'),('Jardim França','Norte'),
('Vila Gustavo','Norte'),('Vila Mazzei','Norte'),('Vila Medeiros','Norte'),('Jardim Brasil','Norte'),
('Jardim Japão','Norte'),('Parque Novo Mundo','Norte'),('Vila Maria','Norte'),('Vila Maria Alta','Norte'),
('Vila Maria Baixa','Norte'),('Parque Edu Chaves','Norte'),('Jaçanã','Norte'),('Vila Constança','Norte'),
('Jardim Guapira','Norte'),('Tremembé','Norte'),('Horto Florestal','Norte'),('Serra da Cantareira','Norte'),
('Mandaqui','Norte'),('Lauzane Paulista','Norte'),('Imirim','Norte'),('Vila Amália','Norte'),
('Vila Aurora','Norte'),('Parque Mandaqui','Norte'),('Vila Sabrina','Norte'),('Vila Isolina Mazzei','Norte'),
('Jardim São Bento','Norte'),('Vila Guilherme','Norte'),('Jardim Pirituba','Norte'),('Pirituba','Norte'),
-- ZONA OESTE
('Butantã','Oeste'),('Cidade Universitária','Oeste'),('Jardim Bonfiglioli','Oeste'),('Rio Pequeno','Oeste'),
('Vila Indiana','Oeste'),('Raposo Tavares','Oeste'),('Jardim Boa Vista','Oeste'),('Jardim Jaqueline','Oeste'),
('Pinheiros','Oeste'),('Alto de Pinheiros','Oeste'),('Vila Madalena','Oeste'),('Vila Beatriz','Oeste'),
('Jardim das Bandeiras','Oeste'),('Sumarezinho','Oeste'),('Cerqueira César','Oeste'),('Jardim Paulistano','Oeste'),
('Jardim América','Oeste'),('Jardim Paulista','Oeste'),('Perdizes','Oeste'),('Sumaré','Oeste'),('Pacaembu','Oeste'),
('Água Branca','Oeste'),('Pompeia','Oeste'),('Vila Anglo Brasileira','Oeste'),('Barra Funda','Oeste'),
('Lapa','Oeste'),('Alto da Lapa','Oeste'),('Vila Leopoldina','Oeste'),('Vila Romana','Oeste'),
('Vila Ipojuca','Oeste'),('Jaguaré','Oeste'),('Jaguara','Oeste'),('Vila Anastácio','Oeste'),
('City América','Oeste'),('City Lapa','Oeste'),('Vila Sônia','Oeste'),('Jardim Colombo','Oeste'),
('Vila Dalva','Oeste'),('Jardim Ester','Oeste'),('Caxingui','Oeste'),('Vila Suzana','Oeste'),
-- CENTRO
('Sé','Centro'),('República','Centro'),('Anhangabaú','Centro'),('Luz','Centro'),('Bom Retiro','Centro'),
('Santa Ifigênia','Centro'),('Campos Elíseos','Centro'),('Consolação','Centro'),('Bela Vista','Centro'),
('Bixiga','Centro'),('Liberdade','Centro'),('Cambuci','Centro'),('Aclimação','Centro'),('Glicério','Centro'),
('Vila Buarque','Centro'),('Higienópolis','Centro'),('Santa Cecília','Centro'),('Canindé','Centro'),
('Ponte Pequena','Centro'),('Bela Cintra','Centro'),('Centro Histórico','Centro'),('Parque Dom Pedro II','Centro');
